{% set name = "oneworld" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a4390c97f5b6b02397fe3844fe9b9e480fe26fa6a2bab492b54bfcd716860b05

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - matplotlib-base >=3.6.2
    - pandas >=1.5.2
    - seaborn >=0.12.2
    - jinja2 >=3.1.2
    - cartopy >=0.21.1

test:
  imports:
    - oneworld
    - os
  requires:
    - pytest
  source_files:
    - tests

about:
  home: https://bitbucket.org/taguilar/oneworld
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python mapping made easy'
  description: |
    OneWorld is a python mapping library intended to make plotting maps 
    with python easy and accessible to everyone. It combines the mapping 
    power of cartopy with the versatility of leaflet and the aesthetics 
    and input structure of seaborn to create both static and interactive maps.
  doc_url: https://oneworld.readthedocs.io
  dev_url: https://bitbucket.org/taguilar/oneworld

extra:
  recipe-maintainers:
    - taguilar
